### ISSUE TITLE
before_filter in version 1.0.4 does not play well with Devise

### ISSUE THREAD

**Issue by AlexMcConnell** [jsanders/angular_rails_csrf#17]
Using Angular to login to Devise, everything breaks after a successful login with version 1.0.4. Version 1.0.3 works fine. Took me a while to figure out it was your gem and not my code! :smile:

**Comment by jsanders** [comment]
Thanks for the report! I'll take a look.

**Comment by prodis** [comment]
Same here. Version 1.0.3 works fine with Angular and Devise, but with version 1.0.4 I get:

```
Started POST "/users/sign_in.json" for ::1 at 2015-12-20 16:16:10 -0200
Processing by Devise::SessionsController#create as JSON
  Parameters: {"user"=>{"email"=>"chico@mineiro.com", "password"=>"[FILTERED]"}, "session"=>{"user"=>{"email"=>"chico@mineiro.com", "password"=>"[FILTERED]"}}}
Can't verify CSRF token authenticity
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)

ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
...
```

**Comment by catuss-a** [comment]
1h to find out it was coming from .4 :(

**Comment by oddg** [comment]
I experienced the same with 1.0.4 while 1.0.3 works perfectly.

**Comment by stefanneculai** [comment]
I have just the same problem. I believe https://github.com/jsanders/angular_rails_csrf/commit/699dc0b3806972fa661d15270037773db472cc98 is causing it.

**Comment by bodrovis** [comment]
https://github.com/jsanders/angular_rails_csrf/pull/15
