### ISSUE TITLE
Not support Rails 5

### ISSUE THREAD

**Issue by matt-hu** [jsanders/angular_rails_csrf#20]
Do we have plans to support Rail 5?

``` console
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.0.0)

  In Gemfile:
    rails (~> 5.0.0)

    angular_rails_csrf was resolved to 1.0.1, which depends on
      rails (< 5, >= 3)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by deepsystm** [comment]
high actually

**Comment by gnuchu** [comment]
Have not had a chance to fully test this fix so your mileage may vary. I've just removed the max rails version from the dependencies and it seems to be working OK for me - just working through an angular/rails tutorial so wouldn't consider this a production ready fix. 

In angular_rails_csrf.gemspec change the following line:
    s.add_runtime_dependency 'rails', '>= 3', '< 5'
to 
    s.add_runtime_dependency 'rails', '>= 3'

and then rebuilding the gem and installing via gem's --local option.

**Comment by theupmachine** [comment]
Just upgraded to Rails 5.  

I've got the following error:
NameError: undefined method `verified_request?' for class `ActionController::API'

triggered by the line:
AngularCsrf.setup

from the file:
config/initializers/angular_csrf.rb

Didn't investigate a lot but seems to appear on rails 5 migration.

**Comment by BideoWego** [comment]
I just saw this too, I looked around for other gems with Rails 5 support but so far no luck. However! Adding this code to the Angular app config solves the issue for me:

```javascript
MyApp.config(
  ["$httpProvider",
  function($httpProvider) {
    var token = $('meta[name=csrf-token]')
      .attr('content');
    $httpProvider
      .defaults
      .headers
      .common['X-CSRF-Token'] = token;
  }]);
```

Sourced from [this StackOverflow post](http://stackoverflow.com/a/14735207/5113832)

**Comment by bodrovis** [comment]
Support for Rails 5 is now added in master, a new version of the gem will be released soon. If anyone still has the problem described here https://github.com/jsanders/angular_rails_csrf/issues/20#issuecomment-248627016 please reopen the issue and list the steps to reproduce the bug (or create a demo app).
