### ISSUE TITLE
Set-Cookie on each request

### ISSUE THREAD

**Issue by platbr** [jsanders/angular_rails_csrf#31]
Using this GEM my application is setting cookie on each request.
I guess it is not good because it don't play well with caching.
For me makes more sense doing it on login/logout actions.

Am i wrong?

**Comment by bodrovis** [comment]
Well, you can surely monkey-patch the code, but in general the behaviour is correct and won't be changed. Some applications have login/logout, some don't have such functionality at all. This gem provides only a very basic, quick (and somewhat hacky) solution to make Angular play nicely with Rails CSRF.
