### ISSUE TITLE
Please, tag releases 4.0.0 and 4.1.0 in github.

### ISSUE THREAD

**Issue by mrexox** [jsanders/angular_rails_csrf#36]
It is very important to see what actually changed in new release version, so I ask you to tag latest releases just as you did with 3.2.0 last time. I am sure, it is very useful for many developers to see if they need to update the gem or not.

**Comment by bodrovis** [comment]
Yes, sorry I forgot to do so. :( I've added the latest release.

**Comment by bodrovis** [comment]
All missing releases should now be present
