### ISSUE TITLE
Does this work for Rails 4?

### ISSUE THREAD

**Issue by julescopeland** [jsanders/angular_rails_csrf#5]
It doesn't seem to work for me...

**Comment by loureirorg** [comment]
Hi @julescopeland , I'm having the same issue (Rails 4.2). How did you solved this?

**Comment by julescopeland** [comment]
This was a very long time ago, so my memory is hazy, but I think it was due to a weird config error...

Iirc, it was this line in the environment file:

config.assets.prefix = ""

Took me weeks to figure that one out.

**Comment by keo64** [comment]
angular
  .module('corsInterceptor', ['ngCookies'])
  .factory(
    'corsInterceptor',
    function ($cookies) {
      return {
        request: function(config) {
          config.headers["X-XSRF-TOKEN"] = $cookies.get('XSRF-TOKEN');
          return config;
        }
      };
    }
  );

It's work!
